local c=cloneref or function(o)return o end
local P,RS,R,U,H=c(game:GetService("Players")),c(game:GetService("ReplicatedStorage")),c(game:GetService("RunService")),c(game:GetService("UserInputService")),c(game:GetService("HttpService"))
local p,pg=P.LocalPlayer,P.LocalPlayer:WaitForChild("PlayerGui")
if getgenv and getgenv().StopAura then pcall(getgenv().StopAura)end
local CF="el2b_cfg.json"
local cfg={codeSniper=true,autoSubmit=true,submitAfter=3,retypeInvalid=false,riddleSolver=false}
pcall(function()if isfile(CF)then local d=H:JSONDecode(readfile(CF))for k,v in pairs(d)do if cfg[k]~=nil then cfg[k]=v end end end end)
local function save()pcall(function()writefile(CF,H:JSONEncode(cfg))end)end
local gu,su,gc,fs,fc=debug.getupvalues or function()return{}end,debug.setupvalue or function()end,getconnections or nil,firesignal or nil,fireclick or nil
local _e,_s,_ap,_sa,_ri,_rs,_lnb,_pt,_pb,_pu=cfg.codeSniper,{},{},cfg.submitAfter,cfg.retypeInvalid,cfg.riddleSolver,"",nil,nil,0
local st,fc_fn,atb,clr
local function isO(i)local x=i for _=1,10 do if not x then break end if x.Name=="EL2B"or x.Name=="SourcesHubRedeemerGui"then return true end x=x.Parent end return false end
local function isV(i)local c=i while c do if c:IsA("GuiObject")and not c.Visible then return false end if c:IsA("ScreenGui")then return c.Enabled end c=c.Parent end return true end
local function getB()local b={}for _,g in ipairs(pg:GetChildren())do if g:IsA("ScreenGui")and g.Enabled and not isO(g)then for _,d in ipairs(g:GetDescendants())do if d:IsA("TextBox")and not isO(d)then b[#b+1]=d end end end end return b end
local function getBtns()local b={}for _,g in ipairs(pg:GetChildren())do if g:IsA("ScreenGui")and g.Enabled and not isO(g)then for _,d in ipairs(g:GetDescendants())do if(d:IsA("TextButton")or d:IsA("ImageButton"))and not isO(d)then local n,pn=d.Name:lower(),(d.Parent and d.Parent.Name or ""):lower()if(n:find("code")or n:find("redeem")or pn:find("code")or pn:find("redeem"))and isV(d)then b[#b+1]=d end end end end end return b end
local function click(b)if not b then return false end local m={function()b.MouseButton1Click:Fire()end,function()b.Activated:Fire()end}if fs then m[#m+1]=function()fs(b.MouseButton1Click)end m[#m+1]=function()fs(b.Activated)end end if gc then m[#m+1]=function()local o,c=pcall(gc,b.MouseButton1Click)if o and type(c)=="table"then for _,x in ipairs(c)do pcall(function()x:Fire()end)end end end end if fc then m[#m+1]=function()fc(b)end end local a=false for _,f in ipairs(m)do a=a or pcall(f)end return a end
local function lost(b)if not b then return false end local a=false if fs then a=pcall(fs,b.FocusLost,true)or a end if gc then local o,c=pcall(gc,b.FocusLost)if o and type(c)=="table"then for _,x in ipairs(c)do local f pcall(function()f=x.Function end)if f and gu and su then local u,p=pcall(gu,f)if u and type(p)=="table"then for i,v in pairs(p)do if type(v)=="boolean"and v==true then pcall(su,f,i,false)end end end end a=pcall(function()if x.Enabled~=false then x:Fire(true)end end)or a end end end return a end
local function submit(c)local g=pg:FindFirstChild("Codes")if g then if g:IsA("ScreenGui")then g.Enabled=true end local f=g:FindFirstChild("Codes")or g if f then if f:IsA("GuiObject")then f.Visible=true end local b,s=nil,nil for _,d in ipairs(f:GetDescendants())do if d:IsA("TextBox")and not isO(d)then b=d break end end for _,d in ipairs(f:GetDescendants())do if(d:IsA("TextButton")or d:IsA("ImageButton"))and not isO(d)then local n,t=d.Name:lower(),""pcall(function()t=d.Text:lower()end)if n:find("submit")or t:find("submit")or n:find("redeem")or t:find("redeem")then s=d break end end end if b then b.Text=c task.wait(0.05)if s then click(s)end lost(b)return true,"pg.codes"end end end local bt=getBtns()for _,b in ipairs(bt)do click(b)task.wait(0.05)end task.wait(0.2)local bx=nil local d=tick()+2 while tick()<d do for _,b in ipairs(getB())do if isV(b)then local n,pn=b.Name:lower(),(b.Parent and b.Parent.Name or ""):lower()if n:find("code")or pn:find("code")or n:find("redeem")or n:find("enter")then bx=b break end end end if bx then break end task.wait(0.1)end if not bx then for _,b in ipairs(getB())do if isV(b)then bx=b break end end end if not bx then return false,"no box"end bx.Text=c task.wait(0.05)local rb=nil local sn={"submit","redeem","claim","confirm","enter","ok"}local pr=bx.Parent for _=1,8 do if not pr then break end for _,d in ipairs(pr:GetDescendants())do if(d:IsA("TextButton")or d:IsA("ImageButton"))and not isO(d)and d~=bx then local n,t=d.Name:lower(),""pcall(function()t=d.Text:lower()end)for _,s in ipairs(sn)do if(n:find(s)or t:find(s))and isV(d)then rb=d break end end end if rb then break end end if rb then break end pr=pr.Parent end if rb then click(rb)end lost(bx)return true,"dyn"end
local CLR={W=Color3.fromRGB(8,8,20),R=Color3.fromRGB(15,15,30),C=Color3.fromRGB(30,30,50),L=Color3.fromRGB(10,10,25),B=Color3.fromRGB(0,255,255),Wh=Color3.fromRGB(180,255,255),T=Color3.fromRGB(200,180,255),D=Color3.fromRGB(100,120,140),A=Color3.fromRGB(0,255,255),G=Color3.fromRGB(0,255,100),Rd=Color3.fromRGB(255,50,50)}
local function addC(p,r)local v=Instance.new("UICorner")v.CornerRadius=UDim.new(0,r)v.Parent=p return v end
local function addS(p,c,t,tr)local v=Instance.new("UIStroke")v.ApplyStrokeMode=Enum.ApplyStrokeMode.Border v.Color=c v.Thickness=t or 1 v.Transparency=tr or 0 v.Parent=p return v end
local function mkL(p,n,t,s,po,ts,c,f)local l=Instance.new("TextLabel")l.Name=n l.Size=s l.Position=po l.BackgroundTransparency=1 l.Text=t l.TextSize=ts l.TextColor3=c l.Font=f or Enum.Font.GothamMedium l.TextXAlignment=Enum.TextXAlignment.Left l.Parent=p return l end
pcall(function()for _,n in ipairs({"EL2B","ACESniperUI","ACECodeSniperUI","AutoTypeCodesUI","ACEPaste"})do local x=game.CoreGui:FindFirstChild(n)or pg:FindFirstChild(n)if x then x:Destroy()end end end)
local GUI=Instance.new("ScreenGui")GUI.Name="EL2B"GUI.ResetOnSpawn,GUI.IgnoreGuiInset,GUI.DisplayOrder=false,true,999
if not pcall(function()GUI.Parent=game.CoreGui end)then GUI.Parent=pg end
local W=Instance.new("Frame")W.Name,W.Size,W.AnchorPoint,W.Position,W.BackgroundColor3,W.BorderSizePixel,W.ClipsDescendants,W.Parent="Window",UDim2.fromOffset(310,370),Vector2.new(1,0),UDim2.new(1,-8,0,8),CLR.W,0,true,GUI
addC(W,14)addS(W,CLR.B,1.5,0.3)
local H=Instance.new("Frame")H.Name,H.Size,H.BackgroundTransparency,H.Parent="Header",UDim2.new(1,0,0,65),1,W
mkL(H,"T","EL2B",UDim2.fromOffset(180,25),UDim2.fromOffset(56,17),15,CLR.Wh,Enum.Font.GothamBold)
local AB=Instance.new("TextButton")AB.Name,AB.Size,AB.Position,AB.BackgroundColor3,AB.BorderSizePixel,AB.AutoButtonColor,AB.Text,AB.Parent="AutoWrite",UDim2.fromOffset(47,24),UDim2.new(1,-64,0,18),CLR.A,0,false,"",H
addC(AB,12)addS(AB,CLR.B,1,0.2)
local KN=Instance.new("Frame")KN.Name,KN.Size,KN.Position,KN.BackgroundColor3,KN.BorderSizePixel,KN.Parent="Knob",UDim2.fromOffset(20,20),UDim2.new(1,-22,0.5,-10),CLR.W,0,AB
addC(KN,10)
local function updAB()AB.BackgroundColor3=_e and CLR.A or CLR.C KN.BackgroundColor3=_e and CLR.W or CLR.Wh KN.Position=_e and UDim2.new(1,-22,0.5,-10)or UDim2.new(0,2,0.5,-10)end
updAB()AB.Activated:Connect(function()_e=not _e cfg.codeSniper=_e save()updAB()end)
local CO local function scrl()if CO then CO.Parent.CanvasPosition=Vector2.new(0,math.max(0,CO.Parent.CanvasSize.Y.Offset-CO.Parent.AbsoluteSize.Y))end end
st=function(m,c)if not CO then return end local t=os.date("%H:%M:%S")local l='<font color="rgb(100,120,140)">['..t..']</font> <font color="rgb('..math.floor(c.R*255)..','..math.floor(c.G*255)..','..math.floor(c.B*255)..')">'..m..'</font>'CO.Text=CO.Text==""and l or CO.Text.."\n"..l scrl()end
local S=Instance.new("Frame")S.Name,S.Size,S.Position,S.BackgroundTransparency,S.Parent="Settings",UDim2.new(1,0,0,154),UDim2.fromOffset(0,65),1,W
local function mkC(n,p,s)local c=Instance.new("Frame")c.Name,c.Position,c.Size,c.BackgroundColor3,c.BackgroundTransparency,c.BorderSizePixel,c.Parent=n,p,s,CLR.R,0.5,0,S addC(c,9)addS(c,CLR.B,1,0.5)return c end
local function mkSB(p,e,n,f)local b=Instance.new("TextButton")b.Name,b.Size,b.Position,b.BackgroundColor3,b.BorderSizePixel,b.AutoButtonColor,b.Text,b.TextSize,b.TextColor3,b.Font,b.Parent="State",UDim2.fromOffset(42,20),UDim2.new(1,-50,0.5,-10),e and CLR.A or CLR.C,0,false,e and"ON"or"OFF",8,e and CLR.W or CLR.D,Enum.Font.GothamBold,p addC(b,6)addS(b,CLR.B,1,e and 0.2 or 0.6)b.Activated:Connect(function()e=not e b.Text=e and"ON"or"OFF"b.BackgroundColor3=e and CLR.A or CLR.C b.TextColor3=e and CLR.Wh or CLR.D f(e)end)return b end
local AC=mkC("Auto",UDim2.fromOffset(17,0),UDim2.fromOffset(135,50))mkL(AC,"T","Auto submit",UDim2.new(1,-58,1,0),UDim2.fromOffset(12,0),11,CLR.Wh)mkSB(AC,cfg.autoSubmit,"Auto",function(v)cfg.autoSubmit=v save()end)
local DC=mkC("Delay",UDim2.fromOffset(17,57),UDim2.fromOffset(276,43))mkL(DC,"T","Submit after",UDim2.fromOffset(145,43),UDim2.fromOffset(12,0),11,CLR.Wh)
local CS=Instance.new("Frame")CS.Size,CS.Position,CS.BackgroundColor3,CS.BackgroundTransparency,CS.Parent=UDim2.fromOffset(96,31),UDim2.new(1,-105,0.5,-15),CLR.W,0.3,DC addC(CS,7)addS(CS,CLR.B,1,0.3)
local M=Instance.new("TextButton")M.Size,M.Position,M.BackgroundColor3,M.Text,M.TextColor3,M.Font,M.Parent=UDim2.fromOffset(25,25),UDim2.fromOffset(3,3),CLR.C,"-",CLR.T,Enum.Font.GothamBold,CS addC(M,5)
local CT=mkL(CS,"C",tostring(_sa),UDim2.fromOffset(28,25),UDim2.fromOffset(34,3),17,CLR.Wh,Enum.Font.GothamBold)CT.TextXAlignment=Enum.TextXAlignment.Center
local PL=Instance.new("TextButton")PL.Size,PL.Position,PL.BackgroundColor3,PL.Text,PL.TextColor3,PL.Font,PL.Parent=UDim2.fromOffset(25,25),UDim2.fromOffset(68,3),CLR.C,"+",CLR.T,Enum.Font.GothamBold,CS addC(PL,5)
M.Activated:Connect(function()_sa=math.max(1,_sa-1)CT.Text=tostring(_sa)cfg.submitAfter=_sa save()end)
PL.Activated:Connect(function()_sa=_sa+1 CT.Text=tostring(_sa)cfg.submitAfter=_sa save()end)
local RC=mkC("Retype",UDim2.fromOffset(17,103),UDim2.fromOffset(276,38))mkL(RC,"T","Retype invalid",UDim2.new(1,-65,1,0),UDim2.fromOffset(12,0),11,CLR.Wh)mkSB(RC,cfg.retypeInvalid,"Retype",function(v)cfg.retypeInvalid=v save()end)
local CN=Instance.new("ScrollingFrame")CN.Size,CN.Position,CN.BackgroundColor3,CN.BackgroundTransparency,CN.CanvasSize,CN.ScrollBarThickness,CN.Parent=UDim2.new(1,-34,0,127),UDim2.fromOffset(17,216),CLR.L,0.6,UDim2.new(0,0,0,0),4,W addC(CN,9)addS(CN,CLR.B,1,0.4)
CO=Instance.new("TextLabel")CO.Size,CO.Position,CO.BackgroundTransparency,CO.RichText,CO.Text,CO.TextSize,CO.Font,CO.TextColor3,CO.TextXAlignment,CO.TextYAlignment,CO.TextWrapped,CO.Parent=UDim2.new(1,-18,0,115),UDim2.fromOffset(9,6),1,true,"",14,Enum.Font.Code,CLR.D,Enum.TextXAlignment.Left,Enum.TextYAlignment.Top,true,CN
CO:GetPropertyChangedSignal("AbsoluteSize"):Connect(function()CN.CanvasSize=UDim2.new(0,0,0,CO.AbsoluteSize.Y+30)end)
do local d,s,p H.InputBegan:Connect(function(i)if i.UserInputType==Enum.UserInputType.MouseButton1 or i.UserInputType==Enum.UserInputType.Touch then d,s,p=true,i.Position,W.Position i.Changed:Connect(function()if i.UserInputState==Enum.UserInputState.End then d=false end end)end end)U.InputChanged:Connect(function(i)if d and(i.UserInputType==Enum.UserInputType.MouseMovement or i.UserInputType==Enum.UserInputType.Touch)then local l=i.Position-s W.Position=UDim2.new(p.X.Scale,p.X.Offset+l.X,p.Y.Scale,p.Y.Offset+l.Y)end end)end
local function getBox()for _,b in ipairs(getB())do if isV(b)then return b end end end
atb=function(t)if not t or t==""then return end local b=getBox()_ap[#_ap+1]=t local c=table.concat(_ap)if b then b.Text=c else st("Captured; open UI",CLR.T)end st("Pasted "..#_ap.."/".._sa,CLR.G)if #_ap>=_sa then _ap={}if cfg.autoSubmit then _pt,_pb,_pu=c,b,os.clock()+5 local o,m=submit(c)if o then st("Redeemed: "..c,CLR.G)else if cfg.retypeInvalid then task.wait(0.1)local rb=getBox()or b if rb then rb.Text=c end end st("Failed: "..tostring(m),CLR.Rd)end end end end
local function watch(o)if not(o:IsA("TextLabel")or o:IsA("TextButton"))then return end local function h(t)if not cfg.retypeInvalid or not _pt or os.clock()>_pu then return end if o:IsDescendantOf(GUI)then return end local l=tostring(t):lower()if l:find("invalid")or l:find("expired")or l:find("already")or l:find("exist")or l:find("not found")then local x,b=_pt,_pb _pt,_pb,_pu=nil,nil,0 task.wait(0.1)local r=getBox()or b if r then r.Text=x st("Invalid - repasted",CLR.T)end end end h(o.Text)o:GetPropertyChangedSignal("Text"):Connect(function()h(o.Text)end)end
for _,o in ipairs(pg:GetDescendants())do watch(o)end pg.DescendantAdded:Connect(function(o)task.wait(0.04)watch(o)end)
local function getR()if _G.PhiNotifyRemote then return _G.PhiNotifyRemote end local n=RS:FindFirstChild("Packages")and RS.Packages:FindFirstChild("Net")if not n then return end local gi=debug.getinfo or debug.info if getgc and gi and gc then for _,d in ipairs(n:GetDescendants())do if d:IsA("RemoteEvent")then local o,c=pcall(gc,d.OnClientEvent)if o then for _,x in ipairs(c)do local f,fn=pcall(function()return x.Function end)if f and type(fn)=="function"then local i,inf=pcall(gi,fn)if i and tostring(inf.short_src or inf.source or""):find("NotificationController")then return d end end end end end end end return nil end
local function tokenize(t)local w={}for x in t:gsub("<[^>]*>",""):gmatch("[%w_]+")do w[#w+1]=x end return w end
local buf={}local function onA(...)local t=tostring(...)t=t:match("^%s*(.-)%s*$")or""if t==""or t:find("%s")then return end for _,w in ipairs(tokenize(t))do buf[#buf+1]=w end if #buf<1 then return end local c=table.concat(buf)buf={}if c==""or _s[c]then return end _s[c]=true task.delay(1.25,function()_s[c]=nil end)atb(c)end
local r=getR()local l if r then if getgenv and getgenv().ACECodeSniperNotifyConnection then pcall(function()getgenv().ACECodeSniperNotifyConnection:Disconnect()end)end l=r.OnClientEvent:Connect(function(...)if _e then pcall(onA,...)end end)if getgenv then getgenv().ACECodeSniperNotifyConnection=l end end
if getgenv then getgenv().StopAura=function()if l then pcall(function()l:Disconnect()end)end if GUI then GUI:Destroy()end end end
print("EL2B Lite Loaded")
